image: demers/python420w4a

variables:
  INFRA_TP5_DB_TYPE: "SQLite"

stages:
  - test
  - deploy
  - validate

utests:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - python3 -m unittest discover -s project -v -p test_*.py

dtests:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - ./run.sh ./project/myCode/SQLiteDB.py &
    - ./run.sh ./project/myAPI/api.py &
    - python3 -m unittest discover -s project -v -p dtest_*.py

deploy-prod:
  stage: deploy 
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_VM_CLOUD") > ~/.ssh/config
    - ssh-add <(echo "$SSH_PRIVATE_KEY_GIT_VMCLOUD") > ~/.ssh/config
    - mkdir -p ~/.ssh/
    - echo -e "Host $VM_CLOUD_IP \n\tFowardAgent yes" > ~/.ssh/config
    - more ~/.ssh/config
    - ssh -o StrictHostKeyChecking=no $VM_CLOUD_USERNAME@$VM_CLOUD_IP "cd ~/infrah2022tp5gbzg/ && git fetch origin master && git reset --hard origin/master && exit"
  only:
    refs:
      - master

validate:
  stage: validate
  script:
    - pip3 install -r requirements.txt
    - python3 -m unittest discover -s project -v -p vtest_*.py
  only:
    refs:
      - master