image: demers/python420w4a

stages:
  - test

utests:
  stage: test
  variables:
    INFRA_TP5_DB_TYPE: "SQLite"
  script:
    - pip3 install -r requirements.txt
    - python3 -m unittest discover -s project -v -p test_*.py

dtests:
  stage: test
  variables:
    INFRA_TP5_DB_TYPE: "SQLite"
  script:
    - pip3 install -r requirements.txt
    - ./run.sh ./project/myAPI/api.py &
    - python3 -m unittest discover -s project -v -p dtest_*.py
